In [1]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.


In [2]:
import numpy as np

In [3]:
np.mean([1,4,3,5,3,5,3])

3.4285714285714284

In [4]:
np.median([1,4,3,5,3,5,3])

3.0

In [5]:
print(np.__version__)

1.26.4


In [ ]:
np.average

# Array

In [6]:
l = [1,2,3,4,5]

In [7]:
type(l)

list

In [9]:
d1= np.array([1,2,3,4])

In [10]:
d1

array([1, 2, 3, 4])

In [11]:
d1.ndim

1

In [12]:
d2 = np.array([[1,2,3],[4,5,6]])

In [13]:
d2

array([[1, 2, 3],
       [4, 5, 6]])

In [14]:
d2.ndim

2

In [16]:
d3 = np.array([[[1,2,3,4],[1,2,3,4],[10,20,30,40]]])

In [17]:
d3

array([[[ 1,  2,  3,  4],
        [ 1,  2,  3,  4],
        [10, 20, 30, 40]]])

In [18]:
d3.ndim

3

In [19]:
np.random.randint(10,50,5)

array([17, 35, 43, 40, 21])

In [20]:
np.random.rand(3,2)

array([[0.07359086, 0.40654625],
       [0.41899013, 0.84937844],
       [0.96428332, 0.21132177]])

In [21]:
np.random.randn(2,2,3)

array([[[-1.18695697,  0.95699033, -0.18679396],
        [-0.87360283,  0.92836341,  0.28350359]],

       [[-0.93838739, -0.24284576,  0.52250222],
        [ 0.46492191,  2.32591963, -0.36565293]]])

In [25]:
np.random.randint(1,6,1)

array([3])